# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t3zhvoTeGeGTvEy6mvOGsUlkhwlu5OgZ
"""

# Mencoba membuat model menggunakan metode SVR (Support Vector Regression)

# Tahapan :
# 1. Ubah data menjadi DataFrame
# 2. Pisahkan atribut dan label
# 3. Latih model SVR
# 4. Buat plot dari model

import pandas as pd

data = pd.read_csv('Salary_Data.csv')
data.head()

# etika hanya terdapat satu atribut pada dataframe, maka atribut tersebut perlu
# diubah bentuknya agar bisa diterima oleh model dari library SKLearn. Untuk
# mengubah bentuk atribut kita membutuhkan library numpy.

import numpy as np

# memisahkan atribut dan label
X = data['YearsExperience']
y = data['Salary']

# mengubah bentuk atribut
X = X[:, np.newaxis]

from sklearn.svm import SVR

# membangun model dengan parameter C, gamma dan kernel
model = SVR(C=1000, gamma=0.05, kernel='rbf')

# melatih model dengan fungsi fit
model.fit(X,y)

import matplotlib.pyplot as plt

# memvisualisasikan model
plt.scatter(X,y)
plt.plot(X, model.predict(X))

