# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ONTRFwsYw3C259E5_HGBmOgteZXW9q98
"""

# membuat model untuk memprediksi harga rumah berdasarkan jumlah kamar yang di
# miliki

import numpy as np

# buat data jumlah kamar
bedrooms = np.array([1,1,2,2,3,4,4,5,5,5])

# data harga rumah. Asumsikan dalam dollar ($)
house_price = np.array([15000, 18000, 27000, 34000, 50000, 68000, 65000, 81000, 85000, 90000])

# menampilkan data dengan scatterplot dari dataset yang di buat sebelumnya
import matplotlib.pyplot as plt

plt.scatter(bedrooms, house_price)

from sklearn.linear_model import LinearRegression

# latih model dengan Linear Regression.fit()
bedrooms = bedrooms.reshape(-1, 1)
linreg = LinearRegression()
linreg.fit(bedrooms, house_price)

# menampilkan plot hubungan antara jumlah kamar dengan harga rumah
plt.scatter(bedrooms, house_price)
plt.plot(bedrooms, linreg.predict(bedrooms))

