# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ONTRFwsYw3C259E5_HGBmOgteZXW9q98
"""

# membuat model Logistic Regression untuk memprediksi apakah seseorang akan
# membeli setelah melihat iklan sebuah produk


# Tahapan
# 1. Ubah dataset menjadi dataframe
# 2. Pisahkan atribut dan label
# 3. Hapus kolom 'User ID'
# 4. Latih Model Logistic Regression
# 5. Evaluasi akurasi model

import pandas as pd

# membaca dataset dan mengubahnya menjadi dataframe
df = pd.read_csv('Social_Network_Ads.csv')

df.head()

# mengecek nilai null tiap atribut dengan fungsi info()
df.info()

# drop kolom yang tidak di perlukan
data = df.drop(columns=['User ID'])

# jalankan proses one-hot encoding dengan pd.get_dummies() karena label dataset kita adalah data kategorial
data = pd.get_dummies(data)
data

# pisahkan antara atribut dan label
prediction = ['Age', 'EstimatedSalary', 'Gender_Female', 'Gender_Male']
X = data[prediction]
y = data['Purchased']

# lakukan normalisasi terhadap data yang kita miliki
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)
scaled_data = scaler.transform(X)
scaled_data = pd.DataFrame(scaled_data, columns = X.columns)
scaled_data.head()

from sklearn.model_selection import train_test_split

# bagi data menjadi train dan test untuk setiap atribut dan label
X_train, X_test, y_train, y_test = train_test_split(scaled_data, y, test_size=0.2, random_state=1)

from sklearn import linear_model

# latih model dengan fungsi fit()
model = linear_model.LogisticRegression()
model.fit(X_train, y_train)

# uji akurasi model
model.score(X_test, y_test)

